name = "TailRoad"
license = "GPLv3"
licenselink = "https://github.com/Sathishbs/tailroad/blob/develop/LICENSE"
description = "Another Hugo theme influenced by MainRoad"

# The home page of the theme, where the source can be found.
homepage = "https://github.com/Sathishbs/tailroad"

# If you have a running demo of the theme.
demosite = "https://tailroad.netlify.app"

tags = ["personal", "blog", "light", "dark", "dark mode", "tailwind"]
features = ["Theme Switching", "Search", "ScrollToTop", "Sidebar", "Widgets"]

# If the theme has a single author
[author]
    name = "Sathish"
    homepage = "https://pujikrish.com"
